name: Build and Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    name: Build, Lint, Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Check code formatting (Spotless)
        run: mvn spotless:check

      - name: Run static analysis (PMD)
        run: mvn pmd:check
        continue-on-error: true

      - name: Build and run unit tests
        run: mvn clean test package

      - name: Run integration tests
        run: mvn verify -DskipTests=false

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: |
            target/*.jar
            target/site/jacoco/

      - name: Report unit test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: JUnit Test Results
          path: target/surefire-reports/*.xml
          reporter: java-junit

      - name: Report integration test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Integration Test Results
          path: target/failsafe-reports/*.xml
          reporter: java-junit

      - name: Run OWASP dependency check
        run: mvn org.owasp:dependency-check-maven:check
        continue-on-error: true

      - name: Upload security report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: target/dependency-check-report.html
